### ISSUE TITLE
Suggested bindings not working

### ISSUE THREAD

**Issue by faceleg** [kmnk/vim-unite-giti#10]
I've added the section from here: https://github.com/kmnk/vim-unite-giti/blob/master/doc/vim-unite-giti.txt#L252 to my vimrc, but none of the bindings (for example `nmap <space>gd <SID>(git-diff-cached)` do anything.

Am I missing a step?

**Comment by kmnk** [comment]
`<SID>(git-diff-cached)` specify [this line](https://github.com/kmnk/vim-unite-giti/blob/master/doc/vim-unite-giti.txt#L278) command.
So you should copy this line too.

**Comment by tracyone** [comment]
hi,how view diff with vimdiff in gait/log?
