### ISSUE TITLE
git grep

### ISSUE THREAD

**Issue by youchan** [kmnk/vim-unite-giti#7]
git grep できて、結果からファイルが開けるとうれしいと思います。

**Comment by kmnk** [comment]
git grep 超使ってるので欲しいなー（ちらっ

**Comment by kmnk** [comment]
テストないですが giti/grep 書いてみました。
https://github.com/kmnk/vim-unite-giti/commit/86a288342831c3cc297782d1a820b1553b9d6254

**Comment by kmnk** [comment]
一旦閉じておきますー

**Comment by youchan** [comment]
:clap: :clap:
