### ISSUE TITLE
Not sure how to use giti/diff_tree/changed_files

### ISSUE THREAD

**Issue by rgrinberg** [kmnk/vim-unite-giti#9]
Running `:Unite giti/diff_tree/changed_files` gives me the following error:

```
error occured on executing "git diff-tree -r --name-only --no-commit-id"
```

Am I doing something wrong?

**Comment by kmnk** [comment]
Please use this source with any commit hash.
such as ...
    :Unite giti/diff_tree/changed_files:cc482aa901ede80c2ef4fa0036074f0a2bb51231

**Comment by rgrinberg** [comment]
OK thanks. Did not know you needed `:`.
